### ISSUE TITLE
How about pagination

### ISSUE THREAD

**Issue by kapuastop** [htr3n/hyde-hyde#18]
How to set up pagination on this theme with Hugo

**Comment by htr3n** [comment]
Hi,
I assume you are asking about pagination for listing of posts in the home page. It can be easily achieved with normal Hugo [pagination techniques](https://gohugo.io/templates/pagination).

What you need to do is go to [`hyde-hyde/layouts/index.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/index.html), then look for the code that walks through the posts and prints out each post's info.

```
{{ range (where .Data.Pages "Type" "not in" (slice "about" "portfolio")).GroupBy "Section" -}}
...
{{ end }}
```

should be changed to something like this.

```
{{ template "_internal/pagination.html" . }}
{{ range .Paginate (where .Data.Pages "Type" "not in" (slice "about" "portfolio")).GroupBy "Section" -}}
...
{{ end }}
```

Hope this works as I'm traveling and have not tried in my setting yet.

**Comment by htr3n** [comment]
As I have heard from you, I will close this issue for now. Please reopen or ask further if you wish.

**Comment by bric3** [comment]
Hi @htr3n, since version 2.0 this part has been rewrittent, as I'm new to hugo, I wonder
how to make pagination working. I've identified two template to override

* `layouts/partials/posts-list.html`
   I'm not sure how to replace this template directive `{{ range . }}` with a `.Paginate` function, idea comming from this [discussion](https://discourse.gohugo.io/t/cant-get-posts-sorted-by-date-in-hyde-hyde-theme/23546). Hugo always fail to render with my tries.

* `layouts/partials/page-list/content.html`
   I just looked at this file to see what the `.` was about it seems it is a `.Data.Pages`

Ive tried many different thing but this usually ends in something like `execute of template failed: template: partials/posts-list.html:1:10: executing "partials/posts-list.html" at <.Paginate>: can't evaluate field Paginate in type page.Pages`

**Comment by bric3** [comment]
Just in case I found a solution, maybe not the best, but it works :

These files needs to be copied over the root of the Hugo site with the same relative path. And modify them as needed

* `layouts/partials/page-list/content.html`
```diff
--- 1/themes/hyde-hyde/layouts/partials/page-list/content.html
+++ 2/layouts/partials/page-list/content.html
@@ -1,6 +1,4 @@
 <span class="section__title">{{ .Title }}</span>
 <ul class="posts">
-    {{ with .Data.Pages }}
-        {{ partial "posts-list.html" . }}
-    {{ end }}
-</ul>
+    {{ partial "posts-list.html" . }}
+</ul>
```

* `layouts/partials/posts-list.html`
```diff
--- 1/themes/hyde-hyde/layouts/partials/posts-list.html
+++ 2/layouts/partials/posts-list.html
@@ -1,6 +1,7 @@
-{{ range . }}
+{{ $paginator := .Paginate (where .Pages "Type" "in" "posts") }}
+{{ template "_internal/pagination.html" . }}
+<br/>
+{{ range $paginator.Pages }}
 <li>
     <a href="{{ .RelPermalink }}" {{if .Draft}}class="draft"{{end}}>{{ .Title }}</a>
       {{if not .Date.IsZero}}
       <time class="pull-right hidden-tablet">{{ .Date.Format (.Site.Params.dateformat | default "Jan 02 '06") }}</time>
@@ -8,3 +9,4 @@
   </span>
 </li>
 {{ end }}
+<br/>
+{{ template "_internal/pagination.html" . }}   
```

Here I’m using the Hugo internal template for pagination but one can image using a custom template. The `.Paginate` directive was taken from [pagination doc](https://gohugo.io/templates/pagination/), however the doc have a slight issue, the where `query` needs to be `where .Pages “Type” “in” “posts”` keyword.
