### ISSUE TITLE
Title is repeated on some pages

### ISSUE THREAD

**Issue by zikes** [htr3n/hyde-hyde#54]
On some pages the `<title>` is repeated. With some digging I found https://github.com/htr3n/hyde-hyde/blob/8c9bb3868b636d795f3ec1ce0f16379f33e5b6d4/layouts/partials/header/meta.html#L10 which led me to believe that the `theTitle` value was being added to twice, so I changed that first line after the else to `$.Scratch.Set` and that fixed it for me.

**Comment by htr3n** [comment]
@zikes I don't quite understand your problems. Did you mean the HTML tag `<title>` or its content keeps repeating? 

The meaning of `{{ if }}` is to check and display the site's title when at the homepage, otherwise, concatenate the page's title with the site's title. 

I'm not sure what are repeated here? Please clarify.

**Comment by htr3n** [comment]
As I have not heard from you for a while, I will close this issue for now. Please reopen to follow up.

**Comment by htr3n** [comment]
@zikes many thanks, I was mistaken due to various copies in my local machine. You are right. I fixed the issue as you suggested.
