### ISSUE TITLE
Social icons are reloading/flashing when navigating

### ISSUE THREAD

**Issue by jcdepth** [htr3n/hyde-hyde#55]
Hi there, something that I've noticed is that when navigating between pages, the social icons seem to "flash", which suggests they may be reloading each time? 

I've looked at your personal live site and this occurs there too, so it doesn't seem to be an issue specific to my environment/machine. Interestingly enough, the demo site doesn't experience this issue: https://themes.gohugo.io/theme/hyde-hyde/.

I've looked at some other themes/sites derived from the original `hyde` theme for Hugo, and they don't seem to have this issue:

- https://npf.io/ (running a fork of the original hyde theme)
- https://enten.github.io/hugo-boilerplate/ (a demo site running the `hyde-y` theme

This is by no means a critical issue, I was just wondering if there's a simple way to change this.

Thanks!

**Comment by htr3n** [comment]
@jcdepth The social icons are part of Font-Awesome. In my personal site, instead of directly loading FA's CSSs, I've used deferred FA JavaScript loading. That's the reason of the flashing/flickering of social icons.

**Comment by jcdepth** [comment]
Thanks for the reply! How would I tweak when Fontawesome is loading?

I'm guessing that because the demo site on gohugo.io doesn't load like this, it may be a setting in how Hugo is building the site?

**Comment by htr3n** [comment]
@jcdepth Sorry for the misleading info. During `hyde-hyde` development, I have switched back and forth between using Fontawesome CSSs or JavaScripts quite few times. The current version of `hyde-hyde` is using FA's JavaScripts in deferred loading styles.

https://github.com/htr3n/hyde-hyde/blob/master/layouts/partials/footer/font-awesome-js.html

That's the main cause of flashing/flickering as the social icons of FA will be loaded almost at the end of the page loading.

The demo site on https://themes.gohugo.io uses the same code base but, I guess, the flickering/flashing is quicker/shorter and perhaps unnoticeable  (e.g. due to faster hosting or caching) compared to my Github site.
