### ISSUE TITLE
Changing the colour of the sidebar

### ISSUE THREAD

**Issue by pointninefour** [htr3n/hyde-hyde#61]
I can't work out for the life of me how to change the colour of the sidebar.

I'm using RStudio's blogdown to set up my blog.

So far I've found 4 files that contain the #300030 colour:
`\themes\hyde-hyde\static\css\hyde-hyde.css`
`\themes\hyde-hyde\assets\scss\hyde-hyde\_variables.scss`
`\themes\hyde-hyde\resources\_gen\assets\scss\scss\hyde-hyde.scss_4fddb88d50abca04f2e7ef77f0bb1c3b.content`
`\themes\hyde-hyde\resources\_gen\assets\scss\scss\hyde-hyde.scss_6a9b89851c76ccc96568016ff9eba049.content`

If I change the colour at these four files, the mobile site works but the desktop site breaks.

Any suggestions on how to adjust the colour on this?

**Comment by htr3n** [comment]
@pointninefour You only need to modify `\themes\hyde-hyde\assets\scss\hyde-hyde\_variables.scss` as `hyde-hyde` is now using SCSS directly. `\themes\hyde-hyde\static\css\hyde-hyde.css` is for the sake of compatibility with Hugo theme demo compilation. The others are generated from the SCSSs by Hugo.

Can you please be more specific about the desktop site is being broken? What is that exactly?

**Comment by pointninefour** [comment]
Thanks @htr3n, no I don't think I'm compiling it correctly. Currently I'm just reloading the theme in using `hugo --theme=hyde-hyde` and nothing is changing. I'm presuming it's more complex than that?

I use RStudio and blogdown which is fed into GitLab which is then deployed using Netlify. 
When I edited the resources, here is what the mobile and desktop versions looked like.

![desktop](https://user-images.githubusercontent.com/38410352/51384996-abd6ae00-1b69-11e9-8b8f-8019aefb2787.PNG)
![mobile](https://user-images.githubusercontent.com/38410352/51385037-c6108c00-1b69-11e9-86b2-199016c80aee.PNG)

**Comment by htr3n** [comment]
@pointninefour as far as I can see, your site is working fine with the new color!? 

The collapsed sidebar is due to mobile mode. Otherwise, it's complained that the non-collapsible sidebar occupies too much space up top ;)

You can try to open your site on bigger screens e.g. laptops or desktops to see how it looks.

**Comment by pointninefour** [comment]
Hi @htr3n, sorry for the confusion, there are two images there, the top one is the desktop site which has lost all formatting, while the bottom one is the mobile site which looks fine.

So to clarify:
When altering the colour in the four files as mentioned in the initial post, I get the two screenshots (i.e. mobile works but desktop loses formatting)
When altering the colour in only `_variables.scss`  and reloading the theme using `hugo --theme=hyde-hyde`, there is no change to the colour, it is still the #300030.

**Comment by htr3n** [comment]
@pointninefour sorry for getting back lately due to travelling. It seems something wrong with the cache in the case of the desktop browser. Have you tried to clean the browser cache? As `hugo` produced versioned CSSs from themes, they might be cached. Or perhaps better to clean the cache of both mobile and desktop browsers and try again to see whether they are still broken. If the mobile version works fine, there should not be any issues with the theme but rather the browsers (local cache, proxy cache, etc.)

**Comment by htr3n** [comment]
@pointninefour would you mind to share your Hugo project and settings (without the content, of course) so that I can have a deeper look? Thanks.

**Comment by pointninefour** [comment]
Thank @htr3n, here is a link to the example site https://github.com/pointninefour/example/tree/master .
