### ISSUE TITLE
Guidance requested on how to customize some styles

### ISSUE THREAD

**Issue by PhilipDaniels** [htr3n/hyde-hyde#63]
The docs say

* Most of the customisable SCSS styles in static-src/scss/hyde-hyde and Hugo templates in hyde-hyde/layouts are modularised and can be altered/adapted easily.

What is the recommended way to do that? I am happy with the overall theme, I just want to tweak a few styles here and there. I've read https://gohugo.io/themes/theme-components/ but can't get overrides to work (hugo docs are really weak on this...). I don't want to edit the files you have created in fear of becoming incompatible with future updates.

I am thinking of just hacking the header partial to include my own stylesheet but I don't know if that is the recommended way.

**Comment by htr3n** [comment]
@PhilipDaniels thanks for your interests. Due to limited spare time, I have tried my best to put on some concrete guidance as much as possible. Nonetheless, customising `hugo` and its themes often require extra efforts to read the docs, play around with an example project, and read or consult the forum (https://discourse.gohugo.io).

Regarding Hugo theme components, I don't use that feature nor implement it in `hyde-hyde`, my experience on that matter would be limited to none.

If I may share some of my experience, just go ahead changing whatever you find fit and reasonable. Don't be afraid of incompatibility or conflicts because that's is what version control like Git/GitHub for. It would be not so difficult to compare and merge the differences with the upstream or other forks.

Nevertheless, the best bet would be to isolate as much as possible your extra code from the original code so that every merging will be smooth. This is the reason I have tried to modularise `hyde-hyde`. 

There is another useful tip: In case you want to try out or override a certain file/template, you just create the same file/template in the root of your project. It will take higher priority over the theme's and therefore your changes will be used instead of the theme. For instance, if I want to override `hyde-hyde/layouts/partials/header/styles.html`, I will create a file `/layouts/partials/header/styles.html` in the root folder of my Hugo project. That's what I have done for some experimenting templates before moving them to the official `hyde-hyde` folders.

Hope this helps.

**Comment by PhilipDaniels** [comment]
Thanks for the reply. I found the docs for hugo very unclear in this area....so I short circuited it simply by making a local copy of your theme 'hyde-hyde-pd' and making my customizations in there. Oh, I also apparently need the 'extended' version of hugo to process SCSS. They don't make it easy...but its working now.
