### ISSUE TITLE
Error when building on Netlify

### ISSUE THREAD

**Issue by THeK3nger** [htr3n/hyde-hyde#77]
Hi guys, 

Trying to build the theme on Netlify, I encountered a `Error: failed to prune cache "assets"` that blocks deployment. With a quick search, this is caused by the fact that the theme has a `resource` folder committed.

This is the main bug: https://github.com/gohugoio/hugo/issues/5745
This is a similar bug in the hell-friend-ng theme: https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/10

**Comment by htr3n** [comment]
@THeK3nger: thanks for your info. 

The `resources` folder is there for a reason. Please see #53 where `resources` was added to make the demo work with Hugo themes site. To consider it a bug, then should it be something to do with the way Hugo dealing with a theme's folders? It's just a folder, Hugo generator can either ignore or overwrite it with or without warning. Due to #53, I wouldn't remove `resources`. 

Does it work for you when removing `resources` and recompile? You can create a fork and remove `resources` in that fork.

**Comment by THeK3nger** [comment]
Yes, sure. I am not asking to remove the resource folder, I know there is a reason for that. I solved by cloning the repo and removing the folder myself. I just wanted to make you (and other people with the same problem) aware of this issue.

**Comment by htr3n** [comment]
@THeK3nger thanks for the heads-up. I haven't used Netlify and am totally unaware of this.
