### ISSUE TITLE
Failed to prune cache "assets" when using hyde-hyde theme

### ISSUE THREAD

**Issue by amitt001** [htr3n/hyde-hyde#78]
Hello @htr3n,
I am trying to use hyde-hyde theme on my website https://github.com/amitt001/kakku.org
But the build is failing with 

`⇒  hugo --gc --minify
Total in 37 ms
Error: failed to prune cache "assets": remove /Users/amittripathi/codes/del/kakku.org/resources/_gen/assets/scss/scss/hyde-hyde.scss_4fddb88d50abca04f2e7ef77f0bb1c3b.content: no such file or directory`

The same thing happens on netlify also. Content of my /resources folder is different and I tried removing and running the command again but that also fails.
I see a similar issue open here https://github.com/gohugoio/hugo/issues/5745

Is this a bug? What's the workaround?

Edit 1:
1. I have a custom theme color, for that, I have my own assets directory with its own scss
2. Removing `rm themes/hyde-hyde/resources/_gen/assets/scss/scss/*` solves the issue locally but it won't solve it on netlify as hyde-hyde is added as a submodule in my project

Edit 2:
1. I renamed the generated content and json file in my projects resources directory and this "works" on the first run but the hugo gc command removes the files and generates a new one. So any subsequent runs fail.

**Comment by amitt001** [comment]
**Update**: I forked the hyde-hyde repo, modified it and removed the resources directory from the theme. Now everything is working.
I sm not super happy with forking your repo as that means I have to manually sync it with updates.

Please let me know the right way to modify scss files in this theme.

This issue can be closed if the resources issue is not a bug and forking is the only solution for my requirement.

**Comment by htr3n** [comment]
@amitt001 I don't use Netlify to try out but I guess the issue is similar to #77. I am afraid I cannot do anything here as removing `resources` would render `hyde-hyde` invalid per the automated scripts from Hugo theme site. 

Nonetheless, you chose the right way. No worries about directly using this repos or fork and use your own repo as the difference is not so significant. You can easily merge any upstream changes into your repos with one or two commands or clicks (if using GUI).
