### ISSUE TITLE
unable to see summary on homepage

### ISSUE THREAD

**Issue by Anu-kriti** [htr3n/hyde-hyde#80]
I am also facing the similar issue.. I am unable to see the summary in my homepage. content/post folder is completely blank in my case. I generated html file of all rmd in content and pasted there still that didnt work.. the layout/index.html also seems fine with same as what I have in examplesite layout
plus the contact option I cant see in disqus, its saying some error in loading that
any idea what should i do here?

_Originally posted by @Anu-kriti in https://github.com/htr3n/hyde-hyde/issues/39#issuecomment-509744137_

**Comment by htr3n** [comment]
@Anu-kriti I'm not quite sure about your issues. Normally with a Hugo theme, you might want to to try with the included `exampleSite` as there might be some configuration parameters needed. With little to none information about your setting, I cannot suspect anything but rather suggest you to try out the `exampleSite` and have a look at a working example using `hyde-hyde` [here](https://github.com/htr3n/htr3n-blog) (it's my home page)

**Comment by Anu-kriti** [comment]
@htr3n Could you please mention me what all setting you required as most of the things goes same as what i see in the examplesite.. but still that page is not showing up.

One additional thing, I also want to add some blog.. when I give that it shows me a blank page with 2 dots and the title only.. The content is missing.. where should the data goes so that it reflect on the site.

**Comment by htr3n** [comment]
Please at least refer and follow the included `exampleSite` as it works for the theme (otherwise, the theme cannot show up in [themes.gohugo.io](https://themes.gohugo.io). For more complex example, [the source of my blog](https://github.com/htr3n/htr3n-blog). Other than that, I am afraid I cannot help when you didn't share any information about your settings. Btw, I saw you mentioned `rmd`. It sounds like you are using R Markdown/Blogdown. I have no experience with that. You might need some helps from the corresponding community.

**Comment by htr3n** [comment]
I close this issue for now. Please feel free to re-open as you wish.

**Comment by Anu-kriti** [comment]
The issue is resolved 
Kindly close it
